# families below

species = [('CO', 'CO'), ('13CO', '13CO'), ('C17O', 'C17O'),
           ('C18O', 'C18O'), ('CF', 'CF'), ('CF+', 'CF+'),
           ('CCH', 'CCH'), ('CH+', 'CH+'), ('CH2_P1/2', 'CH2_P1/2'),
           ('CH2_P3/2', 'CH2_P3/2'), ('CI(C-atom)', 'CI(C-atom)'),
           ('CII', 'CII'), ('CN-', 'CN-'), ('CN', 'CN'), ('CS', 'CS'),
           ('Ha', 'Ha'), ('H20', 'H20'), ('o-H20+', 'o-H20+'),
           ('p-H20+', 'p-H20+'), ('HCN', 'HCN'), ('HNC', 'HNC'),
           ('HCO+', 'HCO+'), ('HF', 'HF'), ('LiH', 'LiH'), ('N2H+', 'N2H+'),
           ('NH3', 'NH3'), ('NII(N+-atom)', 'NII(N+-atom)'),
           ('NO', 'NO'), ('NO+', 'NO+'), ('OI', 'OI'), ('OIII', 'OIII'),
           ('OH+', 'OH+'), ('OH', 'OH'), ('PN', 'PN'),
           ('SiC', 'SiC'), ('SiN', 'SiN'), ('SiO', 'SiO'), ('SO2', 'SO2')]

SpeciesNames = {
    "13CO": "13CO",
    "13COv=0": "13CO",
    "C17O": "C17O",
    "C18O": "C18O",
    "CO": "CO",
    "COv=0": "CO",
    "12CO": "CO",
    "12C16O": "CO",
    "CF": "CF",
    "CF+": "CF+",
    "CF+v=0": "CF+",
    "CCH": "CCH",
    "CCHv=0": "CCH",
    "C2H": "CCH",
    "CH+": "CH+",
    "CH2_P1/2": "CH2_P1/2",
    "CH2_P3/2": "CH2_P3/2",
    "CI(C-atom)": "CI(C-atom)",
    "C": "CI(C-atom)",
    "Ci": "CI(C-atom)",
    "CI": "CI(C-atom)",
    "CII": "CII",
    "C+": "CII",
    "CN-": "CN-",
    "CN": "CN",
    "CNv=0": "CN",
    "CS": "CS",
    "CSv=0": "CS",
    "Ha": "Ha",
    "Halpha": "Ha",
    "Hα": "Ha",
    "H2O": "H2O",
    "H2Ov=0": "H2O",
    "o-H2O+": "o-H2O+",
    "p-H2O+": "p-H2O+",
    "HCN": "HCN",
    "HCNv=0": "HCN",
    "HNC": "HNC",
    "HNCv=0": "HNC",
    "HCO+": "HCO+",
    "HCO+v=0": "HCO+",
    "HF": "HF",
    "LiH": "LiH",
    "LiHv=0": "LiH",
    "N2H+": "N2H+",
    "N2H+v=0": "N2H+",
    "NH3": "NH3",
    "NH3v=0": "NH3",
    "NII(N+-atom)": "NII(N+-atom)",
    "N+": "NII(N+-atom)",
    "Nii": "NII(N+-atom)",
    "NO": "NO",
    "NO+": "NO+",
    "OI": "OI",
    "O": "OI",
    "OIII": "OIII",
    "O++": "OIII",
    "OH+": "OH+",
    "OH": "OH",
    "OHv=0": "OH",
    "PN": "PN",
    "PNv=0": "PN",
    "SiC": "SiC",
    "SiCv=0": "SiC",
    "SiN": "SiN",
    "SiO": "SiO",
    "SiOv=0": "SiO",
    "SO2": "SO2",
    "SO2v=0": "SO2"
}

