"""ok

Revision ID: 0d6f3fad6835
Revises: ea200bef055e
Create Date: 2021-09-28 23:55:58.990491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6f3fad6835'
down_revision = 'ea200bef055e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_edited', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editline', schema=None) as batch_op:
        batch_op.drop_column('is_edited')

    # ### end Alembic commands ###
