"""deleted nullable condition for edit line

Revision ID: 1b35edb5a684
Revises: 85ff8d945220
Create Date: 2022-02-10 00:10:51.857423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b35edb5a684'
down_revision = '85ff8d945220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editline', schema=None) as batch_op:
        batch_op.alter_column('right_ascension',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('declination',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editline', schema=None) as batch_op:
        batch_op.alter_column('declination',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('right_ascension',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
