"""added redshift errors

Revision ID: 2d70ee732bab
Revises: a096d63e788e
Create Date: 2021-06-09 18:05:42.881090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d70ee732bab'
down_revision = 'a096d63e788e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('galaxy', sa.Column('redshift_error', sa.Float(precision=32), nullable=True))
    op.alter_column('galaxy', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('galaxy', 'right_ascension',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('galaxy', 'declination',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('galaxy', 'coordinate_system',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('galaxy', 'lensing_flag',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('galaxy', 'classification',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('line', 'galaxy_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('line', 'j_upper',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('line', 'integrated_line_flux_uncertainty_positive',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('line', 'integrated_line_flux_uncertainty_negative',
               existing_type=sa.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('line', 'integrated_line_flux_uncertainty_negative',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('line', 'integrated_line_flux_uncertainty_positive',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('line', 'j_upper',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('line', 'galaxy_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('galaxy', 'classification',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('galaxy', 'lensing_flag',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('galaxy', 'coordinate_system',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('galaxy', 'declination',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('galaxy', 'right_ascension',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('galaxy', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('galaxy', 'redshift_error')
    # ### end Alembic commands ###
