"""nullable true

Revision ID: 7e83f0eff98c
Revises: ec6d4041dc3b
Create Date: 2021-07-09 11:48:41.288446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e83f0eff98c'
down_revision = 'ec6d4041dc3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.alter_column('integrated_line_flux_uncertainty_positive',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('integrated_line_flux_uncertainty_negative',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.alter_column('integrated_line_flux_uncertainty_negative',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('integrated_line_flux_uncertainty_positive',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
