"""edited in line

Revision ID: 8c99ea705c25
Revises: 76eeed6a134f
Create Date: 2021-10-01 15:50:07.277585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c99ea705c25'
down_revision = '76eeed6a134f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_edited', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editline', schema=None) as batch_op:
        batch_op.drop_column('is_edited')

    # ### end Alembic commands ###
