"""took down the boolean

Revision ID: c4de24fd61ab
Revises: 58e0b47612e0
Create Date: 2021-06-25 15:12:55.843565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4de24fd61ab'
down_revision = '58e0b47612e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.drop_column('symmetrical')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symmetrical', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
