"""independent templine

Revision ID: f6993e4fd404
Revises: 1aa9585a07c7
Create Date: 2021-10-20 09:50:20.706411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6993e4fd404'
down_revision = '1aa9585a07c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tempgalaxy', ['galaxy_id'], ['id'])

    # ### end Alembic commands ###
