"""new fields like university

Revision ID: 04e901496a92
Revises: a2731a3ecd15
Create Date: 2021-05-20 15:36:29.594468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e901496a92'
down_revision = 'a2731a3ecd15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('university', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'website')
    op.drop_column('user', 'university')
    # ### end Alembic commands ###
