"""existed

Revision ID: 177ee3ea2daa
Revises: f6993e4fd404
Create Date: 2021-10-28 17:47:36.123988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177ee3ea2daa'
down_revision = 'f6993e4fd404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_existed_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editline', schema=None) as batch_op:
        batch_op.drop_column('from_existed_id')

    # ### end Alembic commands ###
