"""plus galaxy name in line edit

Revision ID: 473be8cdf721
Revises: ea753a019f94
Create Date: 2021-10-13 12:44:22.549758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473be8cdf721'
down_revision = 'ea753a019f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('galaxy_name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editline', schema=None) as batch_op:
        batch_op.drop_column('galaxy_name')

    # ### end Alembic commands ###
