"""uncertainty nullable, boolean for symmetrical

Revision ID: 58e0b47612e0
Revises: 510a9d79035b
Create Date: 2021-06-24 15:47:07.097225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e0b47612e0'
down_revision = '510a9d79035b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symmetrical', sa.Boolean(), nullable=True))
        batch_op.alter_column('integrated_line_flux_uncertainty_negative',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.alter_column('integrated_line_flux_uncertainty_negative',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('symmetrical')

    # ### end Alembic commands ###
