"""deleted almost all nullable conditions for lines

Revision ID: 5df03b06b0d6
Revises: 1b35edb5a684
Create Date: 2022-02-10 00:12:12.580794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df03b06b0d6'
down_revision = '1b35edb5a684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.alter_column('integrated_line_flux',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('integrated_line_flux_uncertainty_positive',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('right_ascension',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('declination',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.alter_column('integrated_line_flux',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('right_ascension',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('declination',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.alter_column('declination',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('right_ascension',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('integrated_line_flux',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.alter_column('declination',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('right_ascension',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('integrated_line_flux_uncertainty_positive',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('integrated_line_flux',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
