"""Galaxy.lines_per_species added

Revision ID: 671a613393a4
Revises: 5df03b06b0d6
Create Date: 2022-09-21 22:24:24.799871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671a613393a4'
down_revision = '5df03b06b0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lines_per_species', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###
    op.alter_column('line', 'observed_line_frequency', new_column_name='observed_line_redshift')
    op.alter_column('line', 'observed_line_frequency_uncertainty_positive', new_column_name='observed_line_redshift_uncertainty_positive')
    op.alter_column('line', 'observed_line_frequency_uncertainty_negative', new_column_name='observed_line_redshift_uncertainty_negative')
    op.alter_column('templine', 'observed_line_frequency', new_column_name='observed_line_redshift')
    op.alter_column('templine', 'observed_line_frequency_uncertainty_positive', new_column_name='observed_line_redshift_uncertainty_positive')
    op.alter_column('templine', 'observed_line_frequency_uncertainty_negative', new_column_name='observed_line_redshift_uncertainty_negative')
    op.alter_column('editline', 'observed_line_frequency', new_column_name='observed_line_redshift')
    op.alter_column('editline', 'observed_line_frequency_uncertainty_positive', new_column_name='observed_line_redshift_uncertainty_positive')
    op.alter_column('editline', 'observed_line_frequency_uncertainty_negative', new_column_name='observed_line_redshift_uncertainty_negative')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.drop_column('lines_per_species')

    # ### end Alembic commands ###
