"""hi

Revision ID: 76eeed6a134f
Revises: 0d6f3fad6835
Create Date: 2021-09-29 11:44:29.449741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76eeed6a134f'
down_revision = '0d6f3fad6835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_edited', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.drop_column('is_edited')

    # ### end Alembic commands ###
