"""no f_key on ids fron Ids

Revision ID: 85c9b56c8f59
Revises: b537922a8da3
Create Date: 2021-07-06 15:22:06.077493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c9b56c8f59'
down_revision = 'b537922a8da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tempids', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tempids', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tempgalaxy', ['tempgalaxy_id'], ['id'])

    # ### end Alembic commands ###
