"""new coordinates time submitted

Revision ID: 85ff8d945220
Revises: f542e87933ab
Create Date: 2021-12-16 05:58:49.163160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ff8d945220'
down_revision = 'f542e87933ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_submitted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.drop_column('time_submitted')

    # ### end Alembic commands ###
