"""new relationship

Revision ID: a096d63e788e
Revises: 04e901496a92
Create Date: 2021-06-07 22:26:50.526352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a096d63e788e'
down_revision = '04e901496a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('galaxy', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('galaxy', 'right_ascension',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('galaxy', 'declination',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('galaxy', 'coordinate_system',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('galaxy', 'lensing_flag',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('galaxy', 'classification',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('line', 'galaxy_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('line', 'j_upper',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('line', 'integrated_line_flux_uncertainty_positive',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('line', 'integrated_line_flux_uncertainty_negative',
               existing_type=sa.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('line', 'integrated_line_flux_uncertainty_negative',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('line', 'integrated_line_flux_uncertainty_positive',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('line', 'j_upper',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('line', 'galaxy_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('galaxy', 'classification',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('galaxy', 'lensing_flag',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('galaxy', 'coordinate_system',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('galaxy', 'declination',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('galaxy', 'right_ascension',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('galaxy', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
