"""posts table

Revision ID: b36bb1d6c155
Revises: 99177ef37abf
Create Date: 2021-09-22 11:11:02.250274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b36bb1d6c155'
down_revision = '99177ef37abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tempgalaxy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_submitted', sa.DateTime(), nullable=True))

    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_submitted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.drop_column('time_submitted')

    with op.batch_alter_table('tempgalaxy', schema=None) as batch_op:
        batch_op.drop_column('time_submitted')

    # ### end Alembic commands ###
