"""ids table

Revision ID: b537922a8da3
Revises: 3fa30d5deed9
Create Date: 2021-07-06 14:57:55.378291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b537922a8da3'
down_revision = '3fa30d5deed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tempids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tempgalaxy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tempgalaxy_id'], ['tempgalaxy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tempids_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.alter_column('galaxy_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tempids_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('from_existed_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.drop_column('from_existed_id')
        batch_op.drop_column('tempids_id')

    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.alter_column('galaxy_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.drop_column('tempids_id')

    op.drop_table('tempids')
    # ### end Alembic commands ###
