"""deleted ids table

Revision ID: dafd5785b145
Revises: 7e83f0eff98c
Create Date: 2021-07-11 21:43:48.555399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafd5785b145'
down_revision = '7e83f0eff98c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tempids')
    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.drop_column('tempids_id')

    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.drop_column('tempids_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tempids_id', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tempids_id', sa.INTEGER(), nullable=True))

    op.create_table('tempids',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tempgalaxy_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['tempgalaxy_id'], ['tempgalaxy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
