"""added coordinates to lines

Revision ID: dc9554515435
Revises: f7b7c0b5e4bf
Create Date: 2021-12-16 05:49:18.910768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9554515435'
down_revision = 'f7b7c0b5e4bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('right_ascension', sa.Float(precision=32), nullable=False))
        batch_op.add_column(sa.Column('declination', sa.Float(precision=32), nullable=False))
        batch_op.drop_column('admin_notes')

    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_submitted', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_user_email', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('approved_username', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('approved_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_user_email', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('approved_username', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('approved_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('right_ascension', sa.Float(precision=32), nullable=False))
        batch_op.add_column(sa.Column('declination', sa.Float(precision=32), nullable=False))

    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('right_ascension', sa.Float(precision=32), nullable=False))
        batch_op.add_column(sa.Column('declination', sa.Float(precision=32), nullable=False))
        batch_op.drop_column('admin_notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_notes', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('declination')
        batch_op.drop_column('right_ascension')

    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.drop_column('declination')
        batch_op.drop_column('right_ascension')
        batch_op.drop_column('approved_time')
        batch_op.drop_column('approved_username')
        batch_op.drop_column('approved_user_email')

    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.drop_column('approved_time')
        batch_op.drop_column('approved_username')
        batch_op.drop_column('approved_user_email')
        batch_op.drop_column('time_submitted')

    with op.batch_alter_table('editline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_notes', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('declination')
        batch_op.drop_column('right_ascension')

    # ### end Alembic commands ###
