"""edits

Revision ID: ea753a019f94
Revises: 8c99ea705c25
Create Date: 2021-10-12 17:43:08.724945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea753a019f94'
down_revision = '8c99ea705c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editgalaxy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_submitted', sa.DateTime(), nullable=True))

    with op.batch_alter_table('editline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_line_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_submitted', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'galaxy', ['galaxy_id'], ['id'])
        batch_op.drop_column('from_existed_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editgalaxy_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('editline_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'editgalaxy', ['editgalaxy_id'], ['id'])
        batch_op.create_foreign_key(None, 'editline', ['editline_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('editline_id')
        batch_op.drop_column('editgalaxy_id')

    with op.batch_alter_table('editline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_existed_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'editgalaxy', ['galaxy_id'], ['id'])
        batch_op.drop_column('time_submitted')
        batch_op.drop_column('original_line_id')

    with op.batch_alter_table('editgalaxy', schema=None) as batch_op:
        batch_op.drop_column('time_submitted')

    # ### end Alembic commands ###
