"""new tables for temp values

Revision ID: f0b4a309c7aa
Revises: c4de24fd61ab
Create Date: 2021-06-30 10:31:04.859625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b4a309c7aa'
down_revision = 'c4de24fd61ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tempgalaxy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('right_ascension', sa.Float(precision=32), nullable=False),
    sa.Column('declination', sa.Float(precision=32), nullable=False),
    sa.Column('coordinate_system', sa.String(length=128), nullable=False),
    sa.Column('redshift', sa.Float(precision=32), nullable=True),
    sa.Column('redshift_error', sa.Float(precision=32), nullable=True),
    sa.Column('lensing_flag', sa.String(length=32), nullable=False),
    sa.Column('classification', sa.String(length=128), nullable=False),
    sa.Column('notes', sa.String(length=128), nullable=True),
    sa.Column('user_submitted', sa.String(length=128), nullable=True),
    sa.Column('user_email', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('galaxy_id', sa.Integer(), nullable=False),
    sa.Column('j_upper', sa.Integer(), nullable=False),
    sa.Column('integrated_line_flux', sa.Float(precision=32), nullable=False),
    sa.Column('integrated_line_flux_uncertainty_positive', sa.Float(precision=32), nullable=False),
    sa.Column('integrated_line_flux_uncertainty_negative', sa.Float(precision=32), nullable=False),
    sa.Column('peak_line_flux', sa.Float(precision=32), nullable=True),
    sa.Column('peak_line_flux_uncertainty_positive', sa.Float(precision=32), nullable=True),
    sa.Column('peak_line_flux_uncertainty_negative', sa.Float(precision=32), nullable=True),
    sa.Column('line_width', sa.Float(precision=32), nullable=True),
    sa.Column('line_width_uncertainty_positive', sa.Float(precision=32), nullable=True),
    sa.Column('line_width_uncertainty_negative', sa.Float(precision=32), nullable=True),
    sa.Column('observed_line_frequency', sa.Float(precision=32), nullable=True),
    sa.Column('observed_line_frequency_uncertainty_positive', sa.Float(precision=32), nullable=True),
    sa.Column('observed_line_frequency_uncertainty_negative', sa.Float(precision=32), nullable=True),
    sa.Column('detection_type', sa.String(length=32), nullable=True),
    sa.Column('observed_beam_major', sa.Float(precision=32), nullable=True),
    sa.Column('observed_beam_minor', sa.Float(precision=32), nullable=True),
    sa.Column('observed_beam_angle', sa.Float(precision=32), nullable=True),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.String(length=128), nullable=True),
    sa.Column('user_submitted', sa.String(length=128), nullable=True),
    sa.Column('user_email', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['galaxy_id'], ['tempgalaxy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templine')
    op.drop_table('tempgalaxy')
    # ### end Alembic commands ###
