"""new coordinates nullable

Revision ID: f542e87933ab
Revises: dc9554515435
Create Date: 2021-12-16 05:50:59.695068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f542e87933ab'
down_revision = 'dc9554515435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_editline')
    with op.batch_alter_table('editgalaxy', schema=None) as batch_op:
        batch_op.alter_column('right_ascension',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('declination',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('editline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('right_ascension', sa.Float(precision=32), nullable=False))
        batch_op.add_column(sa.Column('declination', sa.Float(precision=32), nullable=False))
        batch_op.drop_column('admin_notes')

    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_submitted', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_user_email', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('approved_username', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('approved_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_user_email', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('approved_username', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('approved_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('right_ascension', sa.Float(precision=32), nullable=False))
        batch_op.add_column(sa.Column('declination', sa.Float(precision=32), nullable=False))

    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('right_ascension', sa.Float(precision=32), nullable=False))
        batch_op.add_column(sa.Column('declination', sa.Float(precision=32), nullable=False))
        batch_op.drop_column('admin_notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_notes', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('declination')
        batch_op.drop_column('right_ascension')

    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.drop_column('declination')
        batch_op.drop_column('right_ascension')
        batch_op.drop_column('approved_time')
        batch_op.drop_column('approved_username')
        batch_op.drop_column('approved_user_email')

    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.drop_column('approved_time')
        batch_op.drop_column('approved_username')
        batch_op.drop_column('approved_user_email')
        batch_op.drop_column('time_submitted')

    with op.batch_alter_table('editline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_notes', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('declination')
        batch_op.drop_column('right_ascension')

    with op.batch_alter_table('editgalaxy', schema=None) as batch_op:
        batch_op.alter_column('declination',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('right_ascension',
               existing_type=sa.FLOAT(),
               nullable=False)

    op.create_table('_alembic_tmp_editline',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('galaxy_id', sa.INTEGER(), nullable=True),
    sa.Column('original_line_id', sa.INTEGER(), nullable=True),
    sa.Column('is_edited', sa.VARCHAR(length=128), nullable=True),
    sa.Column('emitted_frequency', sa.FLOAT(), nullable=False),
    sa.Column('species', sa.VARCHAR(length=32), nullable=True),
    sa.Column('integrated_line_flux', sa.FLOAT(), nullable=False),
    sa.Column('integrated_line_flux_uncertainty_positive', sa.FLOAT(), nullable=True),
    sa.Column('integrated_line_flux_uncertainty_negative', sa.FLOAT(), nullable=True),
    sa.Column('peak_line_flux', sa.FLOAT(), nullable=True),
    sa.Column('peak_line_flux_uncertainty_positive', sa.FLOAT(), nullable=True),
    sa.Column('peak_line_flux_uncertainty_negative', sa.FLOAT(), nullable=True),
    sa.Column('line_width', sa.FLOAT(), nullable=True),
    sa.Column('line_width_uncertainty_positive', sa.FLOAT(), nullable=True),
    sa.Column('line_width_uncertainty_negative', sa.FLOAT(), nullable=True),
    sa.Column('observed_line_frequency', sa.FLOAT(), nullable=True),
    sa.Column('observed_line_frequency_uncertainty_positive', sa.FLOAT(), nullable=True),
    sa.Column('observed_line_frequency_uncertainty_negative', sa.FLOAT(), nullable=True),
    sa.Column('detection_type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('observed_beam_major', sa.FLOAT(), nullable=True),
    sa.Column('observed_beam_minor', sa.FLOAT(), nullable=True),
    sa.Column('observed_beam_angle', sa.FLOAT(), nullable=True),
    sa.Column('reference', sa.VARCHAR(length=128), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=128), nullable=True),
    sa.Column('user_submitted', sa.VARCHAR(length=128), nullable=True),
    sa.Column('user_email', sa.VARCHAR(length=128), nullable=True),
    sa.Column('time_submitted', sa.DATETIME(), nullable=True),
    sa.Column('galaxy_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('right_ascension', sa.FLOAT(), nullable=False),
    sa.Column('declination', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['galaxy_id'], ['galaxy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
