"""no more j_upper 2

Revision ID: f7b7c0b5e4bf
Revises: 177ee3ea2daa
Create Date: 2021-10-31 16:29:10.495710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b7c0b5e4bf'
down_revision = '177ee3ea2daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editline', schema=None) as batch_op:
        batch_op.drop_column('j_upper')

    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.drop_column('j_upper')

    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.drop_column('j_upper')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('j_upper', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('j_upper', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('editline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('j_upper', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
